import { build } from "esbuild";
import { createHash } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const root = new URL("../", import.meta.url);
const result = await build({
  entryPoints: [fileURLToPath(new URL("src/viewer/client.ts", root))],
  bundle: true,
  write: false,
  format: "iife",
  platform: "browser",
  target: "es2022",
  minify: true,
  charset: "ascii",
  legalComments: "none",
});
// Escape HTML script terminators before hashing the exact embedded bytes.
const script = result.outputFiles[0].text.replace(/<\/script/gi, "<\\/script");
const hash = createHash("sha256").update(script).digest("base64");
const output = new URL("src/viewer/client.generated.ts", root);
await mkdir(new URL("src/viewer/", root), { recursive: true });
await writeFile(output, `// Generated by scripts/build-viewer.mjs; do not edit.\nexport const VIEWER_SCRIPT = ${JSON.stringify(script)};\nexport const VIEWER_SCRIPT_HASH = ${JSON.stringify(hash)};\n`);
