import assert from 'node:assert/strict';
import { mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { chromium } from 'playwright-core';
import { renderHtml } from '../dist/index.js';
import { createLucideResolver } from '../dist/icons/lucide.js';

const directory = await mkdtemp(join(tmpdir(), 'archloom-browser-'));
const graph = JSON.parse(await readFile(new URL('../examples/web-system.archloom.json', import.meta.url), 'utf8'));
const icons = await createLucideResolver();
const iconNames = { browser: 'lucide:monitor', api: 'lucide:server', database: 'lucide:database' };
const illustrated = { ...graph, nodes: graph.nodes.map(node => ({ ...node, icon: iconNames[node.id] })) };
const file = join(directory, 'index.html');
await writeFile(file, renderHtml(illustrated, { icons }));
const browser = await chromium.launch({ executablePath: process.env.CHROME_BIN ?? '/usr/bin/google-chrome', headless: true, args: ['--no-sandbox', '--disable-dev-shm-usage'] });
const context = await browser.newContext({ viewport: { width: 1280, height: 820 }, offline: true, reducedMotion: 'no-preference' });
const page = await context.newPage();
const requests = [];
const errors = [];
page.on('request', request => { if (/^https?:/.test(request.url())) requests.push(request.url()); });
page.on('pageerror', error => errors.push(error.message));
page.on('dialog', dialog => { errors.push(`unexpected dialog: ${dialog.message()}`); void dialog.dismiss(); });
const paused = () => page.evaluate(() => document.querySelector('#drawing svg').animationsPaused());
const assertCloseCentered = async browserPage => {
  const alignment = await browserPage.locator('#detail-close').evaluate(button => {
    const box = button.getBoundingClientRect();
    const label = button.parentElement.querySelector('.eyebrow').getBoundingClientRect();
    let inkCenter;
    const icon = button.querySelector('svg');
    if (icon) {
      const bounds = icon.getBBox();
      const point = icon.createSVGPoint(); point.x = bounds.x + bounds.width / 2; point.y = bounds.y + bounds.height / 2;
      inkCenter = point.matrixTransform(icon.getScreenCTM()).y;
    } else {
      const range = document.createRange(); range.selectNodeContents(button);
      const context = document.createElement('canvas').getContext('2d'); context.font = getComputedStyle(button).font;
      const metrics = context.measureText(button.textContent);
      inkCenter = range.getBoundingClientRect().y + metrics.fontBoundingBoxAscent + (metrics.actualBoundingBoxDescent - metrics.actualBoundingBoxAscent) / 2;
    }
    return { button: box.y + box.height / 2, label: label.y + label.height / 2, ink: inkCenter };
  });
  assert.ok(Math.abs(alignment.label - alignment.button) <= .5, `popup header and close control must align vertically: ${JSON.stringify(alignment)}`);
  assert.ok(Math.abs(alignment.ink - alignment.button) <= .5, `close graphic must be vertically centered: ${JSON.stringify(alignment)}`);
};
const clickNode = async id => {
  const point = await page.evaluate(id => {
    const data = JSON.parse(document.querySelector('script[type="application/json"]').textContent);
    const diagram = data.diagrams.dark[0];
    const box = diagram.atlas.nodes[id];
    const svg = document.querySelector('#drawing svg');
    const position = svg.createSVGPoint(); position.x = box.x + box.width / 2; position.y = box.y + box.height / 2;
    const screen = position.matrixTransform(svg.getScreenCTM()); return { x: screen.x, y: screen.y };
  }, id);
  await page.mouse.click(point.x, point.y);
};
try {
  await page.goto(pathToFileURL(file).href);
  await page.locator('#drawing > svg').first().waitFor();
  assert.equal(await page.locator('#details').isVisible(), false, 'details stay closed until a card or line is selected');
  assert.equal(await page.locator('#view-select option').count(), 2);
  assert.equal(await page.locator('#drawing [data-kind="node"]').count(), 3);
  const pillPoint = await page.evaluate(() => {
    const data = JSON.parse(document.querySelector('script[type="application/json"]').textContent);
    const diagram = data.diagrams.dark[0]; const line = diagram.atlas.lines.find(line => line.id === 'query');
    const svg = document.querySelector('#drawing svg'); const point = svg.createSVGPoint();
    point.x = line.pill.x + line.pill.width / 2 + diagram.atlas.shift.x;
    point.y = line.pill.y + line.pill.height / 2 + diagram.atlas.shift.y;
    const screen = point.matrixTransform(svg.getScreenCTM()); return { x: screen.x, y: screen.y };
  });
  await page.mouse.click(pillPoint.x, pillPoint.y);
  assert.match(await page.locator('#detail-title').textContent(), /Read query/);
  assert.match(await page.locator('#drawing [data-kind="line"][data-id="query"] .line-path').evaluate(path => getComputedStyle(path).mask), /line-mask-\d+/, 'line highlight is cut out around its label');
  assert.equal(await page.locator('#drawing [data-kind="line"][data-id="https"] .line-path').evaluate(path => getComputedStyle(path).mask), 'none', 'idle lines carry no mask');
  await page.screenshot({ path: join(directory, 'line-selected-dark.png') });
  assert.equal(await page.locator('#details').getAttribute('role'), 'dialog');
  await page.locator('#detail-close').click();
  assert.equal(await page.locator('#details').isVisible(), false);
  await clickNode('api');
  assert.match(await page.locator('#detail-title').textContent(), /API/);
  assert.match(await page.locator('#detail-body').textContent(), /Validates the request/);
  await assertCloseCentered(page);
  const popup = await page.locator('#details').boundingBox();
  const area = await page.locator('#canvas').boundingBox();
  assert.ok(popup.x >= area.x && popup.y >= area.y && popup.x + popup.width <= area.x + area.width && popup.y + popup.height <= area.y + area.height, 'popup is contained in the canvas');
  const selected = await page.locator('#drawing [data-kind="node"][data-id="api"]').boundingBox();
  assert.ok(popup.x >= selected.x + selected.width || popup.x + popup.width <= selected.x || popup.y >= selected.y + selected.height || popup.y + popup.height <= selected.y, 'popup sits beside the selected card, not over it');
  assert.match(await page.locator('#detail-eyebrow').textContent(), /app · Application/);
  await page.screenshot({ path: join(directory, 'popup-node-dark.png') });
  const popupScale = await page.locator('#drawing').getAttribute('data-scale');
  await page.mouse.move(popup.x + 30, popup.y + 80); await page.mouse.wheel(0, 120);
  assert.equal(await page.locator('#drawing').getAttribute('data-scale'), popupScale, 'scrolling popup must not zoom the canvas');
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#details').isVisible(), false);
  assert.equal(await page.locator('#drawing [data-kind="node"][data-id="api"]').evaluate(node => node === document.activeElement), true, 'Escape restores selection focus');
  await clickNode('api');
  await page.mouse.click(area.x + 12, area.y + 12);
  assert.equal(await page.locator('#details').isVisible(), false, 'background click dismisses popup');
  const scale = Number(await page.locator('#drawing').getAttribute('data-scale'));
  await page.locator('#zoom-in').click();
  assert.ok(Number(await page.locator('#drawing').getAttribute('data-scale')) > scale);
  const beforePan = await page.locator('#drawing').getAttribute('data-x');
  const viewport = await page.locator('#canvas').boundingBox();
  await page.mouse.move(viewport.x + viewport.width - 16, viewport.y + viewport.height - 16);
  await page.mouse.down(); await page.mouse.move(viewport.x + viewport.width - 100, viewport.y + viewport.height - 32); await page.mouse.up();
  assert.notEqual(await page.locator('#drawing').getAttribute('data-x'), beforePan);
  await page.locator('#fit').click();
  await page.screenshot({ path: join(directory, 'architecture-dark.png') });
  await page.locator('#zoom-in').click();
  const zoomed = await page.locator('#drawing').getAttribute('data-scale');
  await page.locator('#theme-toggle').click();
  assert.match(await page.locator('#drawing').innerHTML(), /#0969da/);
  assert.equal(await page.locator('#drawing').getAttribute('data-scale'), zoomed, 'switching theme keeps the zoom level');
  await page.locator('#fit').click();
  await page.screenshot({ path: join(directory, 'architecture-light.png') });
  await clickNode('api');
  await assertCloseCentered(page);
  await page.screenshot({ path: join(directory, 'popup-node-light.png') });
  await page.locator('#theme-toggle').click();
  assert.equal(await page.locator('#details').isVisible(), false, 'theme/view switch dismisses popup');
  await page.locator('#view-select').selectOption('flow-load-records');
  assert.equal(await page.locator('#drawing [data-kind="node"]').count(), 3);
  assert.equal(await page.locator('#drawing [data-kind="line"]').count(), 4);
  await page.locator('#play-toggle').click(); assert.equal(await paused(), true);
  await page.locator('#play-toggle').click(); assert.equal(await paused(), false);
  await page.locator('#step-next').click();
  assert.match(await page.locator('#detail-title').textContent(), /GET \/records/);
  await page.keyboard.press('Enter');
  assert.match(await page.locator('#detail-title').textContent(), /Read records/, 'Enter on the step button keeps stepping');
  await page.locator('#drawing [data-kind="node"][data-id="api"]').focus(); await page.keyboard.press('Enter');
  assert.match(await page.locator('#detail-title').textContent(), /API/);
  await page.screenshot({ path: join(directory, 'flow-dark.png') });
  const ids = await page.locator('[id]').evaluateAll(elements => elements.map(element => element.id));
  assert.equal(new Set(ids).size, ids.length, 'active DOM IDs must not duplicate');

  const hostile = { ...graph, title: '</title><script>globalThis.archloomXss=1</script>', nodes: graph.nodes.map(node => ({ ...node, summary: '</script><script>globalThis.archloomXss=1</script><img src="https://example.invalid/pixel">' })) };
  const hostileFile = join(directory, 'hostile.html'); await writeFile(hostileFile, renderHtml(hostile));
  await page.goto(pathToFileURL(hostileFile).href); await clickNode('api');
  assert.equal(await page.evaluate(() => globalThis.archloomXss), undefined);
  assert.match(await page.locator('#detail-body').textContent(), /<script>/);
  assert.equal(await page.locator('img,iframe,foreignObject').count(), 0);

  const flows = graph.flows;
  const repeated = { ...graph, flows: [...flows, ...flows.map(flow => ({ ...flow, id: 'second' }))], views: [{ id: 'combined', title: 'Two flows', lens: 'data-flow' }] };
  const repeatedFile = join(directory, 'repeated.html'); await writeFile(repeatedFile, renderHtml(repeated));
  await page.goto(pathToFileURL(repeatedFile).href);
  assert.equal(await page.locator('#drawing [data-kind="node"]').count(), 6);
  assert.equal(await page.locator('#drawing [data-kind="line"]').count(), 8);

  const reduced = await browser.newContext({ viewport: { width: 1280, height: 820 }, offline: true, reducedMotion: 'reduce' });
  const reducedPage = await reduced.newPage(); await reducedPage.goto(pathToFileURL(file).href);
  assert.equal(await reducedPage.evaluate(() => document.querySelector('#drawing svg').animationsPaused()), true);
  await reduced.close();
  const mobile = await browser.newContext({ viewport: { width: 360, height: 740 }, offline: true });
  const mobilePage = await mobile.newPage(); await mobilePage.goto(pathToFileURL(file).href);
  await mobilePage.locator('#view-select').selectOption('flow-load-records');
  await mobilePage.locator('#step-next').click();
  await assertCloseCentered(mobilePage);
  const mobilePopup = await mobilePage.locator('#details').boundingBox();
  const mobileCanvas = await mobilePage.locator('#canvas').boundingBox();
  assert.ok(mobilePopup.x >= mobileCanvas.x && mobilePopup.y >= mobileCanvas.y && mobilePopup.x + mobilePopup.width <= mobileCanvas.x + mobileCanvas.width && mobilePopup.y + mobilePopup.height <= mobileCanvas.y + mobileCanvas.height, 'mobile popup stays fully inside canvas');
  await mobilePage.screenshot({ path: join(directory, 'popup-mobile.png') });
  await mobilePage.locator('#detail-close').click();
  assert.equal(await mobilePage.locator('#details').isVisible(), false);
  await mobile.close();
  assert.deepEqual(requests, [], 'canvas must attempt no HTTP requests');
  assert.deepEqual(errors, [], 'browser must not report script errors or dialogs');
  console.log(`Browser checks passed: native popup positioning/close/focus/mobile, geometry clicks, pan/zoom, themes, flow steps, pause/play, keyboard, duplicate flow headings, XSS and reduced motion; HTTP requests: 0. Screenshots: ${directory}`);
} finally { await context.close(); await browser.close(); }
