import { ArchloomError } from "./errors.js";
import { parseGraph, type Theme } from "./graph.js";
import { renderAll, type RenderAllOptions } from "./render.js";
import { VIEWER_SCRIPT, VIEWER_SCRIPT_HASH } from "./viewer/client.generated.js";

const escapeHtml = (text: string): string => text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");
const serialize = (value: unknown): string => JSON.stringify(value).replace(/</g, "\\u003c").replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029");

// Embedding escapes the SVG, so the page is roughly three times this.
const MAX_EMBEDDED_SVG = 16 * 1024 * 1024;

/** A self-contained, read-only canvas. Rendering and icon resolution happen offline. */
export function renderHtml(input: unknown, options: RenderAllOptions = {}): string {
  const graph = parseGraph(input);
  // Let the renderer validate the original options before choosing the other theme.
  const initial = renderAll(graph, options);
  // Read the theme the renderer validated, not the caller's option a second time.
  const initialTheme: Theme = initial[0]?.theme ?? "dark";
  // Every view is embedded in both themes; refuse before rendering the second copy.
  if (initial.reduce((size, diagram) => size + diagram.svg.length, 0) * 2 > MAX_EMBEDDED_SVG)
    throw new ArchloomError("INVALID_GRAPH", "views are too large to embed in one canvas; render fewer or smaller views");
  const oppositeTheme = initialTheme === "dark" ? "light" : "dark";
  const opposite = renderAll(graph, { ...options, theme: oppositeTheme });
  const diagrams = initialTheme === "dark" ? { dark: initial, light: opposite } : { dark: opposite, light: initial };
  const payload = serialize({ graph, diagrams, initialTheme });
  const csp = `default-src 'none'; script-src 'sha256-${VIEWER_SCRIPT_HASH}'; connect-src 'none'; style-src 'unsafe-inline'; img-src data: blob:; form-action 'none'; base-uri 'none'; object-src 'none'`;
  return `<!doctype html>
<html lang="en" data-theme="${initialTheme}">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="${escapeHtml(csp)}"><title>${escapeHtml(graph.title)} · Archloom</title>
<style>
:root{color-scheme:dark;--bg:#0d1117;--panel:#161b22;--raised:#262c36;--text:#e6edf3;--muted:#9198a1;--border:#30363d;--accent:#58a6ff;--dot:#6e768138;--shadow:0 8px 28px #0006;font-family:ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
:root[data-theme=light]{color-scheme:light;--bg:#f4f5f7;--panel:#fff;--raised:#eceef1;--text:#1f2328;--muted:#59636e;--border:#d1d9e0;--accent:#0969da;--dot:#6e768147;--shadow:0 8px 28px #1f232814}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);height:100dvh;overflow:hidden}.stage{position:relative;height:100%}
#canvas{position:absolute;inset:0;overflow:hidden;overflow:clip;background-color:var(--bg);background-image:radial-gradient(circle,var(--dot) var(--grid-dot,1px),transparent calc(var(--grid-dot,1px) + .5px));background-size:var(--grid-size,18px) var(--grid-size,18px);background-position:var(--grid-x,0) var(--grid-y,0);touch-action:none;user-select:none;cursor:grab}#canvas.panning{cursor:grabbing}#canvas:focus-visible{outline:2px solid var(--accent);outline-offset:-2px}#drawing{position:absolute;left:0;top:0;transform-origin:0 0}#drawing>svg{display:block;width:100%;height:100%}#drawing>.hit-overlay{position:absolute;inset:0;overflow:visible;pointer-events:none}.hit{cursor:pointer;pointer-events:all;fill:transparent;stroke:transparent;stroke-width:2;vector-effect:non-scaling-stroke}.hit.line-path{fill:none;pointer-events:stroke;stroke-width:18}.hit:focus,.hit.selected{outline:none;stroke:var(--accent);stroke-width:2;fill:#80b4ff16}.hit.line-path:focus,.hit.line-path.selected,.line-hit:focus>.line-path,.line-hit.selected>.line-path{fill:none;stroke:var(--accent);stroke-width:5;stroke-opacity:.65;mask:var(--line-mask,none)}.line-hit:focus>.line-pill,.line-hit.selected>.line-pill{stroke:var(--accent);fill:#80b4ff16}
.hud{position:absolute;z-index:5;display:flex;align-items:center;gap:2px;padding:3px;border:1px solid transparent;border-radius:11px;background:color-mix(in srgb,var(--panel) 55%,transparent);-webkit-backdrop-filter:blur(10px);backdrop-filter:blur(10px);color:var(--muted);font-size:12px;transition:box-shadow .12s,opacity .12s}.hud:hover,.hud:focus-within{background:color-mix(in srgb,var(--panel) 94%,transparent);border-color:var(--border);color:var(--text);box-shadow:var(--shadow)}.stage:has(#canvas.panning) .hud{opacity:.35;pointer-events:none}.hud[hidden]{display:none}.top-left{top:16px;left:16px;max-width:calc(100% - 180px)}.top-right{top:16px;right:16px}.bottom-left{bottom:16px;left:16px}.bottom-center{bottom:16px;left:50%;transform:translateX(-50%)}
button,select{font:inherit;color:inherit;border:0;border-radius:8px;background:none;cursor:pointer}button{display:inline-flex;align-items:center;justify-content:center;gap:4px;min-width:32px;height:32px;padding:0 8px}button:hover,select:hover{background:var(--raised)}button:disabled{opacity:.4;cursor:default;background:none}button[hidden]{display:none}button:focus-visible,select:focus-visible{outline:2px solid var(--accent);outline-offset:1px}button svg{display:block;flex:none;width:16px;height:16px;fill:none;stroke:currentColor;stroke-width:1.5;stroke-linecap:round;stroke-linejoin:round}
:root[data-theme=dark] .i-moon,:root[data-theme=light] .i-sun,#play-toggle[aria-pressed=true] .i-play,#play-toggle[aria-pressed=false] .i-pause{display:none}
#system-title{margin:0 4px 0 8px;font-size:13px;font-weight:600;color:var(--text);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;min-width:0}.separator{flex:none;width:1px;height:16px;margin:0 4px;background:var(--border)}#view-select{height:32px;min-width:0;max-width:260px;padding:0 26px 0 8px;text-overflow:ellipsis;appearance:none;background-image:linear-gradient(45deg,transparent 50%,currentColor 50%),linear-gradient(135deg,currentColor 50%,transparent 50%);background-size:4px 4px;background-repeat:no-repeat;background-position:calc(100% - 14px) 14px,calc(100% - 10px) 14px}#view-select option{background:var(--panel);color:var(--text)}#zoom-level{min-width:42px;text-align:center;font-variant-numeric:tabular-nums}
#details{position:absolute;z-index:10;width:min(300px,calc(100% - 24px));max-height:calc(100% - 24px);background:var(--panel);border:1px solid var(--border);border-radius:12px;overflow:auto;padding:12px 16px 16px;box-shadow:var(--shadow),0 2px 6px #0002;cursor:auto;user-select:text}#details[hidden]{display:none}#details:focus{outline:none}#details:focus-visible{outline:2px solid var(--accent);outline-offset:2px}.popup-header{position:sticky;top:0;z-index:1;display:flex;align-items:center;justify-content:space-between;gap:12px;margin-right:-8px;background:var(--panel)}.eyebrow{font-size:10px;font-weight:650;letter-spacing:.12em;text-transform:uppercase;color:var(--muted);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}#detail-close{flex:none;width:32px;padding:0;color:var(--muted)}#detail-title{font-size:16px;line-height:1.3;margin:2px 0 0;overflow-wrap:anywhere}#detail-body{font-size:13px;line-height:1.55;overflow-wrap:anywhere;white-space:pre-wrap}#detail-body p{margin:8px 0 0;color:var(--text)}#detail-body dl{display:grid;grid-template-columns:auto 1fr;gap:6px 14px;align-items:baseline;margin:12px 0 0;padding-top:12px;border-top:1px solid var(--border)}#detail-body dt{font-size:10px;font-weight:650;letter-spacing:.12em;text-transform:uppercase;color:var(--muted)}#detail-body dd{margin:0;color:var(--text);min-width:0}#detail-body dd.mono{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:12px;color:var(--muted)}noscript{position:absolute;inset:auto 0 0;padding:24px}
@media(max-width:760px){.hud button{min-width:40px;height:40px}#view-select{height:40px;max-width:150px;background-position:calc(100% - 14px) 18px,calc(100% - 10px) 18px}.top-left{top:12px;left:12px;max-width:calc(100% - 160px)}.top-right{top:12px;right:12px}.bottom-left{bottom:12px;left:12px}.bottom-center{bottom:12px;left:auto;right:12px;transform:none}#system-title,.top-left .separator,#zoom-level{display:none}#detail-close{min-width:40px;min-height:40px}}
@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto}.hud{transition:none}}
</style></head>
<body><main class="stage"><div class="hud top-left"><h1 id="system-title"></h1><span class="separator"></span><select id="view-select" aria-label="Diagram view" title="Diagram view"></select></div>
<nav class="hud top-right" aria-label="Canvas actions"><button id="theme-toggle" type="button"><svg class="i-sun" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><circle cx="12" cy="12" r="4"/><path d="M12 3v2M12 19v2M3 12h2M19 12h2M5.6 5.6 7 7M17 17l1.4 1.4M5.6 18.4 7 17M17 7l1.4-1.4"/></svg><svg class="i-moon" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M20 14.5A8 8 0 0 1 9.5 4a8 8 0 1 0 10.5 10.5Z"/></svg></button><button id="download" type="button" aria-label="Download SVG" title="Download SVG"><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M12 4v11M7.5 10.5 12 15l4.5-4.5M5 19h14"/></svg></button></nav>
<section id="canvas" tabindex="0" aria-label="Diagram canvas. Drag background to pan; use zoom controls or the mouse wheel."><div id="drawing"></div><aside id="details" role="dialog" aria-labelledby="detail-title" tabindex="-1" hidden><div class="popup-header"><div class="eyebrow" id="detail-eyebrow"></div><button id="detail-close" type="button" aria-label="Close details"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true" focusable="false"><path d="M6 6 18 18M18 6 6 18"/></svg></button></div><h2 id="detail-title"></h2><div id="detail-body" aria-live="polite"></div></aside></section>
<nav class="hud bottom-left" aria-label="Zoom"><button id="zoom-out" type="button" aria-label="Zoom out" title="Zoom out"><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M6 12h12"/></svg></button><output id="zoom-level" aria-label="Zoom level"></output><button id="zoom-in" type="button" aria-label="Zoom in" title="Zoom in"><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M6 12h12M12 6v12"/></svg></button><button id="fit" type="button" aria-label="Fit to screen" title="Fit to screen"><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M9 4H4v5M15 4h5v5M9 20H4v-5M15 20h5v-5"/></svg></button></nav>
<nav class="hud bottom-center" id="playback" aria-label="Playback"><button id="play-toggle" type="button"><svg class="i-play" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M8 5.5v13l10-6.5Z"/></svg><svg class="i-pause" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M9 6v12M15 6v12"/></svg></button><button id="step-next" type="button" aria-label="Next message" title="Next message">Next<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="m10 7 5 5-5 5"/></svg></button></nav>
<noscript>Enable JavaScript to explore this offline diagram.</noscript></main>
<script id="viewer-data" type="application/json">${payload}</script>
<script>${VIEWER_SCRIPT}</script></body></html>`;
}
